version: '3.9'

services:

  # web:
  #   build: ./project
  #   ports:
  #     - 8004:8000
  #   command: uvicorn main:app --host 0.0.0.0 --reload
  #   volumes:
  #     - ./project:/usr/src/app
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis

  # worker:
  #   build: ./project
  #   command: celery -A worker.celery worker --loglevel=info
  #   volumes:
  #     - ./project:/usr/src/app
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - web
  #     - redis

  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      # POSTGRES_USER: postgres  # default
      POSTGRES_PASSWORD: rootpass
      # POSTGRES_DB: postgres  # default
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      # - ../2. Init Database:/docker-entrypoint-initdb.d
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 256M
    # command: >
    #   postgres -c max_connections=1000
    #            -c shared_buffers=256MB
    #            -c effective_cache_size=768MB
    #            -c maintenance_work_mem=64MB
    #            -c checkpoint_completion_target=0.7
    #            -c wal_buffers=16MB
    #            -c default_statistics_target=100
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped
    # tty: true
    # stdin_open: true

volumes:
  pgdata:
    # driver: local